import threading
import time
import pygame
import os
from queue import Queue, Empty

class DS4Handler(threading.Thread):
    def __init__(self, signals, command_queue):
        super().__init__()
        self.daemon = True
        self.signals = signals
        self.command_queue = command_queue
        self.joystick = None
        self.joysticks = [] # Store persistent joystick objects

    def _initialize_pygame(self):
        """Initializes Pygame and its subsystems with detailed logging."""
        print("DEBUG: DS4Handler: Initializing Pygame...")
        try:
            os.environ['SDL_VIDEODRIVER'] = 'dummy'
            pygame.init()
            pygame.joystick.init()
            print(f"DEBUG: DS4Handler: Pygame initialized successfully.")
            return True
        except Exception as e:
            print(f"FATAL: DS4Handler: Pygame failed to initialize: {e}")
            return False

    def _set_device(self, joystick_index):
        """Sets or clears the active joystick device using the persistent list."""
        print(f"DEBUG: DS4Handler: Received SET_DEVICE command for index {joystick_index}")
        if self.joystick:
            try:
                print(f"DEBUG: DS4Handler: Quitting previous joystick instance.")
                self.joystick.quit()
            except Exception as e:
                print(f"ERROR: DS4Handler: Exception while quitting joystick: {e}")
            finally:
                self.joystick = None

        if joystick_index is not None:
            try:
                if len(self.joysticks) > joystick_index:
                    self.joystick = self.joysticks[joystick_index] # Use the stored object
                    print(f"DEBUG: DS4Handler: Joystick object retrieved from list for index {joystick_index}. Initializing...")
                    self.joystick.init()
                    print(f"DEBUG: DS4Handler: Successfully initialized joystick: {self.joystick.get_name()}")
                else:
                    print(f"ERROR: DS4Handler: Invalid joystick index {joystick_index}. Stored list length is {len(self.joysticks)}.")
                    self.signals.gamepad_disconnected.emit()
            except pygame.error as e:
                print(f"ERROR: DS4Handler: Pygame error while setting device: {e}")
                self.joystick = None
                self.signals.gamepad_disconnected.emit()
        else:
            print("DEBUG: DS4Handler: Joystick index is None, device cleared.")

    def _refresh_devices(self):
        """Scans for gamepads, stores them persistently, and emits a signal with their info."""
        print("DEBUG: DS4Handler: Received REFRESH_DEVICES command.")
        # Quit all joysticks in the old list before refreshing
        for joy in self.joysticks:
            joy.quit()
        self.joysticks.clear()

        pygame.joystick.quit()
        pygame.joystick.init()
        pygame.event.clear() # Discard any events generated by re-initialization

        gamepads_info = []
        count = pygame.joystick.get_count()
        print(f"DEBUG: DS4Handler: Found {count} joysticks.")
        for i in range(count):
            try:
                joystick = pygame.joystick.Joystick(i)
                self.joysticks.append(joystick) # Store the object
                gamepads_info.append({'name': joystick.get_name(), 'index': i})
            except pygame.error as e:
                print(f"DEBUG: DS4Handler: Could not get info for joystick {i}: {e}")
                continue

        print(f"DEBUG: DS4Handler: Emitting gamepad list: {gamepads_info}")
        self.signals.gamepad_list_updated.emit(gamepads_info)

    def _handle_events(self):
        try:
            for event in pygame.event.get():
                # The refresh logic now handles device changes more gracefully.
                # A full refresh is triggered by the main UI thread.
                if event.type == pygame.JOYDEVICEADDED or event.type == pygame.JOYDEVICEREMOVED:
                    self.signals.device_changed.emit()

                if self.joystick and self.joystick.get_init():
                    if hasattr(event, 'instance_id') and event.instance_id == self.joystick.get_instance_id():
                        self._process_game_event(event)
        except pygame.error as e:
            print(f"ERROR: DS4Handler: Pygame error in event loop: {e}. Disconnecting.")
            self.joystick = None
            self.signals.gamepad_disconnected.emit()

    def run(self):
        if not self._initialize_pygame():
            return

        running = True
        while running:
            try:
                command = self.command_queue.get_nowait()
                print(f"DEBUG: DS4Handler: Command received from queue: {command}")
                cmd_type = command.get('type')

                if cmd_type == 'SET_DEVICE':
                    self._set_device(command.get('index'))
                elif cmd_type == 'REFRESH_DEVICES':
                    self._refresh_devices()
                elif cmd_type == 'STOP':
                    running = False
            except Empty:
                pass

            if self.joystick:
                self._handle_events()

            time.sleep(0.01)

        pygame.quit()
        print("DEBUG: DS4Handler: Thread stopped.")

    def _process_game_event(self, event):
        self.signals.raw_event.emit(str(event))
        if event.type == pygame.JOYAXISMOTION:
            # Axis mapping for DS4 controller
            # 0,1: Left Stick | 2,3: Right Stick | 4: L2 Trigger | 5: R2 Trigger
            # 6,7,8: Accel X,Y,Z | 9,10,11: Gyro X,Y,Z
            axis_map = {
                0: 'ABS_X', 1: 'ABS_Y', 2: 'ABS_RX', 3: 'ABS_RY',
                4: 'ABS_Z', 5: 'ABS_RZ',
                6: 'ABS_HAT0X', 7: 'ABS_HAT0Y', 8: 'ABS_HAT0Z', # Accel
                9: 'ABS_HAT1X', 10: 'ABS_HAT1Y', 11: 'ABS_HAT1Z'  # Gyro
            }
            if event.axis in axis_map:
                # Separate triggers from other axes
                if event.axis in [4, 5]:
                    self.signals.trigger_event.emit(axis_map[event.axis], event.value)
                else:
                    self.signals.stick_event.emit(axis_map[event.axis], event.value)
        elif event.type == pygame.JOYBUTTONDOWN or event.type == pygame.JOYBUTTONUP:
            pressed = (event.type == pygame.JOYBUTTONDOWN)
            button_map = {
                0: 'BTN_SOUTH', 1: 'BTN_EAST', 2: 'BTN_WEST', 3: 'BTN_NORTH',
                9: 'BTN_TL', 10: 'BTN_TR', 7: 'BTN_THUMBL', 8: 'BTN_THUMBR',
                11: 'DPAD_UP', 12: 'DPAD_DOWN', 13: 'DPAD_LEFT', 14: 'DPAD_RIGHT',
                6: 'BTN_START', 4: 'BTN_SELECT', 5: 'BTN_MODE'
            }
            if event.button in button_map:
                self.signals.button_event.emit(button_map[event.button], pressed)
